apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: demo-policy-generator
placementBindingDefaults:
  name: demo-placement-binding
policyDefaults:
  namespace: policies
  placement:
    name: demo-placement-rule
    clusterSelectors:
      name: local-cluster
  remediationAction: inform
  severity: medium
policies:
  - name: policy-helm
    manifests:
      - path: templates  
